;;; decklet-edit-test.el --- Tests for decklet-edit.el -*- lexical-binding: t; -*-

(require 'decklet-test-helpers)

;; ---------------------------------------------------------------------------
;; Edit flow: batch operations and delegation branches
;; ---------------------------------------------------------------------------
;; These tests verify branch behavior in `decklet-edit-delete' and
;; `decklet-edit-archive' without requiring tabulated-list UI setup.

(ert-deftest decklet-test-edit-mark-with-region-marks-selected-lines ()
  (with-temp-buffer
    (insert "a\nb\nc\n")
    (let ((decklet-edit--marked (make-hash-table :test 'equal))
          (decklet-edit--mark-overlays (make-hash-table :test 'equal)))
      (cl-letf (((symbol-function 'tabulated-list-get-id)
                 (lambda ()
                   (pcase (line-number-at-pos)
                     (1 11)
                     (2 22)
                     (3 33)
                     (_ nil)))))
        (decklet-edit--mark-region (point-min)
                                   (save-excursion
                                     (goto-char (point-min))
                                     (forward-line 2)
                                     (point))))
      (should (gethash 11 decklet-edit--marked))
      (should (gethash 22 decklet-edit--marked))
      (should-not (gethash 33 decklet-edit--marked)))))

(ert-deftest decklet-test-edit-mark-uses-region-branch-when-active ()
  (let ((called nil)
        (deactivated nil)
        (moved nil))
    (cl-letf (((symbol-function 'use-region-p) (lambda () t))
              ((symbol-function 'region-beginning) (lambda () 10))
              ((symbol-function 'region-end) (lambda () 20))
              ((symbol-function 'decklet-edit--mark-region)
               (lambda (beg end)
                 (setq called (list beg end))))
              ((symbol-function 'deactivate-mark)
               (lambda () (setq deactivated t)))
              ((symbol-function 'goto-char)
               (lambda (pos) (setq moved pos)))
              ((symbol-function 'beginning-of-line) (lambda () nil))
              ((symbol-function 'forward-line) (lambda (&rest _) nil)))
      (decklet-edit-mark-at-point))
    (should (equal called '(10 20)))
    (should deactivated)
    (should (= moved 20))))

(ert-deftest decklet-test-edit-mark-keeps-raw-multiline-word-id ()
  (with-temp-buffer
    (insert "line1↵line2\n")
    (let ((decklet-edit--marked (make-hash-table :test 'equal))
          (decklet-edit--mark-overlays (make-hash-table :test 'equal)))
      (cl-letf (((symbol-function 'use-region-p) (lambda () nil))
                ((symbol-function 'tabulated-list-get-id)
                 (lambda () 42)))
        (decklet-edit-mark-at-point))
      (should (gethash 42 decklet-edit--marked))
      (pcase-let ((`(,row-ov . ,mark-ov)
                   (gethash 42 decklet-edit--mark-overlays)))
        (should (overlayp row-ov))
        (should (overlayp mark-ov))))))

(ert-deftest decklet-test-edit-delete-marked-branch-runs-batch-delete ()
  (let ((deleted '())
        (ensured nil)
        (cleared nil)
        (restored nil))
    (cl-letf (((symbol-function 'decklet-edit--marked-card-ids)
               (lambda () '(1 2)))
              ((symbol-function 'decklet-edit--nearest-surviving-card-id)
               (lambda (_ids) 3))
              ((symbol-function 'count-screen-lines)
               (lambda (&rest _) 7))
              ((symbol-function 'decklet-edit--ensure-not-current)
               (lambda (ids) (setq ensured ids)))
              ((symbol-function 'yes-or-no-p) (lambda (&rest _) t))
              ((symbol-function 'decklet-delete-card)
               (lambda (card-id) (push card-id deleted)))
              ((symbol-function 'decklet-edit--unmark-all)
               (lambda () (setq cleared t)))
              ((symbol-function 'decklet-edit--line-of-card-id)
               (lambda (card-id)
                 (when (= card-id 3) 5)))
              ((symbol-function 'decklet-edit--restore-position)
               (lambda (line win-line)
                 (setq restored (list line win-line))))
              ((symbol-function 'message) (lambda (&rest _) nil)))
      (decklet-edit-delete))
    (should (equal ensured '(1 2)))
    (should (equal (sort deleted #'<) '(1 2)))
    (should cleared)
    (should (equal restored '(5 7)))))

(ert-deftest decklet-test-edit-nearest-surviving-card-id-prefers-forward-on-tie ()
  (with-temp-buffer
    (insert "a\nb\nc\nd\n")
    (goto-char (point-min))
    (forward-line 2)
    (cl-letf (((symbol-function 'tabulated-list-get-id)
               (lambda ()
                 (pcase (line-number-at-pos)
                   (1 11)
                   (2 22)
                   (3 33)
                   (4 44)
                   (_ nil)))))
      (should (= (decklet-edit--nearest-surviving-card-id '(33)) 44))
      (should (= (decklet-edit--nearest-surviving-card-id '(22 33)) 44)))))

(ert-deftest decklet-test-edit-entries-render-multiline-word-and-hint-inline ()
  (cl-letf (((symbol-function 'decklet-db--select-cards)
             (lambda (&rest _)
               '((:card-id 42 :word "line1\nline2" :added "20250101T000000Z"
                           :last-review nil :due "20250102T000000Z"
                           :state "learning" :step nil :stability nil
                           :difficulty nil :hint "hint1\nhint2" :back nil)))))
    (let* ((decklet-edit--filter 'all)
           (tabulated-list-sort-key nil)
           (entry (car (decklet-edit--entries)))
           (columns (cadr entry)))
      (should (= (car entry) 42))
      (should (string= (aref columns 0) "line1↵line2"))
      (should (string= (aref columns 1) "hint1↵hint2")))))

(ert-deftest decklet-test-edit-delete-without-marks-delegates-to-single-delete ()
  (let ((delegated nil))
    (cl-letf (((symbol-function 'decklet-edit--marked-card-ids) (lambda () nil))
              ((symbol-function 'decklet-edit-delete-card)
               (lambda () (setq delegated t))))
      (decklet-edit-delete))
    (should delegated)))

(ert-deftest decklet-test-edit-archive-uses-unarchive-in-archived-filter ()
  (let ((decklet-edit--filter 'archived)
        (unarchived nil)
        (archived nil))
    (cl-letf (((symbol-function 'decklet-edit--marked-card-ids) (lambda () nil))
              ((symbol-function 'decklet-edit-unarchive-card)
               (lambda () (setq unarchived t)))
              ((symbol-function 'decklet-edit-archive-card)
               (lambda () (setq archived t))))
      (decklet-edit-archive))
    (should unarchived)
    (should-not archived)))

(ert-deftest decklet-test-edit-archive-marked-in-archived-filter-unarchives-and-restores ()
  (let ((decklet-edit--filter 'archived)
        (unarchived '())
        (archived nil)
        (ensured nil)
        (cleared nil)
        (restored nil))
    (cl-letf (((symbol-function 'decklet-edit--marked-card-ids)
               (lambda () '(1 2)))
              ((symbol-function 'decklet-edit--nearest-surviving-card-id)
               (lambda (_ids) 3))
              ((symbol-function 'count-screen-lines)
               (lambda (&rest _) 6))
              ((symbol-function 'decklet-edit--ensure-not-current)
               (lambda (ids) (setq ensured ids)))
              ((symbol-function 'yes-or-no-p) (lambda (&rest _) t))
              ((symbol-function 'decklet-unarchive-card)
               (lambda (card-id) (push card-id unarchived)))
              ((symbol-function 'decklet-archive-card)
               (lambda (&rest _) (setq archived t)))
              ((symbol-function 'decklet-edit--unmark-all)
               (lambda () (setq cleared t)))
              ((symbol-function 'decklet-edit--line-of-card-id)
               (lambda (card-id)
                 (when (= card-id 3) 4)))
              ((symbol-function 'decklet-edit--restore-position)
               (lambda (line win-line)
                 (setq restored (list line win-line))))
              ((symbol-function 'message) (lambda (&rest _) nil)))
      (decklet-edit-archive))
    (should (equal ensured '(1 2)))
    (should (equal (sort unarchived #'<) '(1 2)))
    (should-not archived)
    (should cleared)
    (should (equal restored '(4 6)))))

(ert-deftest decklet-test-edit-archive-marked-in-all-filter-archives-and-restores ()
  (let ((decklet-edit--filter 'all)
        (unarchived nil)
        (archived '())
        (ensured nil)
        (cleared nil)
        (restored nil))
    (cl-letf (((symbol-function 'decklet-edit--marked-card-ids)
               (lambda () '(1 2)))
              ((symbol-function 'decklet-edit--nearest-surviving-card-id)
               (lambda (_ids) 3))
              ((symbol-function 'count-screen-lines)
               (lambda (&rest _) 8))
              ((symbol-function 'decklet-edit--ensure-not-current)
               (lambda (ids) (setq ensured ids)))
              ((symbol-function 'yes-or-no-p) (lambda (&rest _) t))
              ((symbol-function 'decklet-unarchive-card)
               (lambda (&rest _) (setq unarchived t)))
              ((symbol-function 'decklet-archive-card)
               (lambda (card-id) (push card-id archived)))
              ((symbol-function 'decklet-edit--unmark-all)
               (lambda () (setq cleared t)))
              ((symbol-function 'decklet-edit--line-of-card-id)
               (lambda (card-id)
                 (when (= card-id 3) 6)))
              ((symbol-function 'decklet-edit--restore-position)
               (lambda (line win-line)
                 (setq restored (list line win-line))))
              ((symbol-function 'message) (lambda (&rest _) nil)))
      (decklet-edit-archive))
    (should (equal ensured '(1 2)))
    (should (equal (sort archived #'<) '(1 2)))
    (should-not unarchived)
    (should cleared)
    (should (equal restored '(6 8)))))

(ert-deftest decklet-test-edit-delete-marked-without-survivor-skips-restore ()
  (let ((restored nil))
    (cl-letf (((symbol-function 'decklet-edit--marked-card-ids)
               (lambda () '(1 2)))
              ((symbol-function 'decklet-edit--nearest-surviving-card-id)
               (lambda (_ids) nil))
              ((symbol-function 'count-screen-lines)
               (lambda (&rest _) 3))
              ((symbol-function 'decklet-edit--ensure-not-current)
               (lambda (&rest _) nil))
              ((symbol-function 'yes-or-no-p) (lambda (&rest _) t))
              ((symbol-function 'decklet-delete-card)
               (lambda (&rest _) nil))
              ((symbol-function 'decklet-edit--unmark-all)
               (lambda () nil))
              ((symbol-function 'decklet-edit-refresh)
               (lambda () nil))
              ((symbol-function 'decklet-edit--line-of-card-id)
               (lambda (_card-id) nil))
              ((symbol-function 'decklet-edit--restore-position)
               (lambda (&rest _) (setq restored t)))
              ((symbol-function 'message) (lambda (&rest _) nil)))
      (decklet-edit-delete))
    (should-not restored)))

(ert-deftest decklet-test-edit-delete-marked-cancelled-skips-side-effects ()
  (let ((deleted nil)
        (cleared nil)
        (refreshed nil)
        (restored nil)
        (ensured nil))
    (cl-letf (((symbol-function 'decklet-edit--marked-card-ids)
               (lambda () '(1 2)))
              ((symbol-function 'decklet-edit--nearest-surviving-card-id)
               (lambda (_ids) 3))
              ((symbol-function 'count-screen-lines)
               (lambda (&rest _) 5))
              ((symbol-function 'decklet-edit--ensure-not-current)
               (lambda (ids) (setq ensured ids)))
              ((symbol-function 'yes-or-no-p) (lambda (&rest _) nil))
              ((symbol-function 'decklet-delete-card)
               (lambda (&rest _) (setq deleted t)))
              ((symbol-function 'decklet-edit--unmark-all)
               (lambda () (setq cleared t)))
              ((symbol-function 'decklet-edit-refresh)
               (lambda () (setq refreshed t)))
              ((symbol-function 'decklet-edit--line-of-card-id)
               (lambda (&rest _) 3))
              ((symbol-function 'decklet-edit--restore-position)
               (lambda (&rest _) (setq restored t)))
              ((symbol-function 'message) (lambda (&rest _) nil)))
      (decklet-edit-delete))
    (should (equal ensured '(1 2)))
    (should-not deleted)
    (should-not cleared)
    (should-not refreshed)
    (should-not restored)))

(ert-deftest decklet-test-edit-archive-marked-cancelled-skips-side-effects ()
  (let ((decklet-edit--filter 'all)
        (archived nil)
        (unarchived nil)
        (cleared nil)
        (refreshed nil)
        (restored nil)
        (ensured nil))
    (cl-letf (((symbol-function 'decklet-edit--marked-card-ids)
               (lambda () '(1 2)))
              ((symbol-function 'decklet-edit--nearest-surviving-card-id)
               (lambda (_ids) 3))
              ((symbol-function 'count-screen-lines)
               (lambda (&rest _) 5))
              ((symbol-function 'decklet-edit--ensure-not-current)
               (lambda (ids) (setq ensured ids)))
              ((symbol-function 'yes-or-no-p) (lambda (&rest _) nil))
              ((symbol-function 'decklet-archive-card)
               (lambda (&rest _) (setq archived t)))
              ((symbol-function 'decklet-unarchive-card)
               (lambda (&rest _) (setq unarchived t)))
              ((symbol-function 'decklet-edit--unmark-all)
               (lambda () (setq cleared t)))
              ((symbol-function 'decklet-edit-refresh)
               (lambda () (setq refreshed t)))
              ((symbol-function 'decklet-edit--line-of-card-id)
               (lambda (&rest _) 3))
              ((symbol-function 'decklet-edit--restore-position)
               (lambda (&rest _) (setq restored t)))
              ((symbol-function 'message) (lambda (&rest _) nil)))
      (decklet-edit-archive))
    (should (equal ensured '(1 2)))
    (should-not archived)
    (should-not unarchived)
    (should-not cleared)
    (should-not refreshed)
    (should-not restored)))

(provide 'decklet-edit-test)
;;; decklet-edit-test.el ends here
